export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const RECEIVED_NEWSDATA = 'RECEIVED_NEWSDATA';
export const UPDATE_PAGENUMBER = 'UPDATE_PAGENUMBER';
export const UPDATE_HIDDEN_NEWSID = 'UPDATE_HIDDEN_NEWSID';